title: Javascript Tutorial
description: A javascript tutorial written by Noah Loomans

url: http://brianmaierjr.github.com/long-haul
baseurl: "/javascript-tutorial"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

# navigation:
#  - title: Home
#    url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

# google_analytics: "UA-58263416-1"
